namespace :antlr do
  dir = File.join(Rails.root, 'lib', 'emulation_system', 'parsing', 'antlr_parser')
  gname = 'waffle'

  desc "Generate ANTLR3 parser for Waffle grammar"
  task :generate => :clear do
    grammar = File.join(dir, gname + '.g')
    sh "antlr3 #{grammar} -o #{dir}"
  end

  desc "Clear files generated by ANTLR3"
  task :clear do
    %w{.tokens Lexer.py Lexer.pyc Parser.py Parser.pyc}.each do |ext|
      f = File.join(dir, gname + ext)
      rm f if File.exist? f
    end
  end
end
